version: '3.8'

services:
  main-service-dev:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: main-service-dev
    working_dir: /app
    command: dotnet watch run --no-hot-reload
    ports:
      - "5063:5062"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5062
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    volumes:
      - .:/app
      - ${VOLUME_BASE_PATH}:/app/storage
      - /app/bin
      - /app/obj
    networks:
      - validasi-ta-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  validasi-ta-network:
    driver: bridge
