FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /src
EXPOSE 5062

COPY ["main-service.csproj", "./"]
RUN dotnet restore "main-service.csproj"

COPY . .

ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5062"]
