version: '3.8'

services:
  main-service:
    container_name: main-service-dotnet
    build: .
    ports:
      - "5063:5062"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5062
    volumes:
      - validasi-storage:/app/storage
    networks:
      - validasi-ta-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  validasi-storage:
    name: validasi-ta-storage

networks:
  validasi-ta-network:
    driver: bridge
