FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /src
EXPOSE 5062
ENV ASPNETCORE_HTTP_PORTS=5062

COPY ["main-service.csproj", "./"]
RUN dotnet restore "main-service.csproj"

COPY . .

ENTRYPOINT ["dotnet", "watch", "run"]
